apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cntk-my-module
spec:
  destination:
    namespace: cntk
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/cntk/my-module
    repoURL: https://github.com/cloud-native-toolkit-test/provider-test
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
